### ISSUE TITLE
Publish Helm Chart to a Registry

### ISSUE THREAD

**Issue by hegerdes** [wacken89/hetzner-load-balancer-prometheus-exporter#10]
Is it possible to publish the helm chart that is included in this repo to a public registry like https://artifacthub.io/?

It is possible via a [GitHub Action](https://github.com/helm/chart-releaser-action) and can even be stored as a GitHub pages file if artifacthub is not suitable

If not feel free to close this

**Comment by wacken89** [comment]
Hi there! Thanks for reaching out. My apologies for the delayed response. I have your task in my backlog and I'll make sure to get it done as soon as possible. Thanks for your understanding!

**Comment by hegerdes** [comment]
No worries!

I'm happy to hear that. I recently implemented a Helm Repo via GH Actions & Pages myself. If you want to go that route (since I think it is the solution with the least external dependencies and  overhead) I can make a PR to save you some time. This way you would only need to review it. 

If you want to get into that yourself [this](https://github.com/hegerdes/demo-app-flask-nuxt/blob/master/.github/workflows/helm.yml#L45) might be a slight inspiration.

**Comment by wacken89** [comment]
Hello, the registry for the chart has been created information can be found at this link:
https://wacken89.github.io/hetzner-load-balancer-prometheus-exporter/
