### ISSUE TITLE
Support for secret files

### ISSUE THREAD

**Issue by Radiergummi** [wacken89/hetzner-load-balancer-prometheus-exporter#11]
It would be great to be able to pass the API token as a file instead of an environment variable, using secret mounts in Docker swarm, for example. This could be implemented by allowing to set the `API_TOKEN_FILE` environment variable to a path of a file containing the actual token; the code would need to check whether that variable is set and points to a readable file, then read that; otherwise, fall back to the `API_TOKEN` environment variable.  
If you're interested, I'm happy to send a PR!

**Comment by wacken89** [comment]
Hi there! It's great to see you contributing! This product is open-source, which means you're welcome to make as many requests as you'd like. We appreciate your help and hope you enjoy being part of our community!

**Comment by wacken89** [comment]
PR #12  resolved the problem, thanks to @Radiergummi's efforts.
