### ISSUE TITLE
[Idea] Add service/target status

### ISSUE THREAD

**Issue by codebude** [wacken89/hetzner-load-balancer-prometheus-exporter#7]
Hi @wacken89 ,

First let me thank you for this great project! 
I would like to place an idea/feature request. Would it be possible to add metrics (probably Gauges) to show the health status of the services (or service targets). If I understood the Hetzner API documentation, there should be a health state available via API. 

Best regards,
Raffael

**Comment by wacken89** [comment]
Closed by PR https://github.com/wacken89/hetzner-load-balancer-prometheus-exporter/pull/8
